use_frameworks!

platform :ios, '10.0'

target 'IMSdk-Ios-demo_Example' do
#  pod 'IMSdk',:git =>"https://github.com/TmmTmmIM/IMSdk-iOS.git"

  target 'IMSdk-Ios-demo_Tests' do
    inherit! :search_paths


  end
end
